Vagrant.configure("2") do |config|
	#konfigurasi box untuk sistem operasi debian jessie 64bit
	config.vm.box = "debian/jessie64"
	config.vm.provider "virtualbox" do |vb|
	vb.name = "batch001"
	#konfigurasi virtual box ram 1GB cpu 1 core
	vb.memory = "1024"
	vb.cpus = "1"
#konfigurasi provisioning
	config.vm.provision "shell", path: "install.sh"

	#konfigurasi network 
	#port forwarding
	config.vm.network "private_network", ip: "192.168.2.20"

	config.vm.network "forwarded_port", guest: 80, host: 10080
	end
end
